export enum CreditStatusEnums {
  CREDIT = 100,
  INSTALLMENTS_CREDIT = 200,
  MOZAREBEH = 300,
  PREPAID_INSTALLS = 400,
  DISCOUNT = 500,
  DISCOUNT_STORE_IN_BALANCE = 501,
  DISCOUNT_STORE_IN_BALANCE_AND_WALLET = 502,
  SHETAB = 503,
  DISCOUNT_CLOSELOOP= 600,
  DISCOUNT_CLOSELOOP_STORE_IN_BALANCE_AND_WALLET = 601,
  STORE_IN_BALANCE = 700,
  GIFT_CARD = 800,
  ORGANIZATION = 900,
  ORGANIZATION_AND_WALLET = 901,
  ORGANIZATION_AND_WALLET_BALANCE_IN_STORE=902
}

export enum CreditChargeStatusEnums {
  Transferable = 100,
  UnTransferable = 200,
  SecondTransfer = 300,
}

export enum CoBenefit {
  PrimaryBenefit = 2.5,
}