import * as mongoose from 'mongoose';

export const BasketStoreSchema = new mongoose.Schema({
  hasIranianShop: { type: Boolean, required: true },
  hasOwnShop: { type: Boolean, required: true },
  isHyper: { type: Boolean, required: true, default: false },
  ownShopTitle: { type: String },
  ownShopUrl: { type: String },
  ownShopAbout: { type: String },
  hasDelivery: { type: Boolean, default: false },
  deliveryPrice: { type: Number },
  deliveryDescription: { type: String },
  hasPishtaz: { type: Boolean, default: false },
  pishtazPrice: { type: Number },
  pishtazDescription: { type: String },
  hasFreeShipping: { type: Boolean, default: false },
  freeShippingAmount: { type: Number },
  hasDeliveryToWholeCountry: { type: Boolean, default: true, required: true },
  deliveryProvince: { type: String, required: false, default: '' },
  deliveryCity: { type: String, required: false, default: '' },
  deliveryTimeout: { type: Number, min: 0, max: 6 },
  metaTitle: { type: String },
  metaDescription: { type: String },
  user: { type: mongoose.SchemaTypes.ObjectId, ref: 'User' },
  status: { type: Boolean, default: true },
  title: { type: String },
  tels: [{ tel: { type: String } }],
  description: { type: String },
  about: { type: String },
  email: { type: String },
  mipg: { type: mongoose.SchemaTypes.ObjectId, ref: 'Mipg', default: null },
  nickname: { type: String },
  logo: { type: String },
  banner: { type: String },
  banners: [{ img: { type: String } }],
  mobiles: { type: [Number], default: [] },
  hasCashOnDelivery: { type: Boolean, default: false },
  transfer: {
    type: { type: Number, default: 1 },
    karmozd: { type: Number, default: 10 },
  },
});
