export enum SimcardRechargeCodeEnum {
  HAMRAHAVAL_DESIRED = 1002,
  HAMRAHAVAL_YOUNG = 1004,
  HAMRAHAVAL_WOMAN,

  IRANCEL_NORMAL = 20,
  IRANCEL_SPECIAL = 19,
  IRANCEL_PERMANENT = 0,

  RIGHTEL_NORMAL = 2,
  RIGHTEL_SPECIAL,
}
